rock/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'rock.views.index_view', name='index'),
    url(r'^login$', 'rock.views.login_view', name='login'),
    url(r'^logout$', 'rock.views.logout_view', name='logout'),
    url(r'^signup$', 'rock.views.signup_view', name='signup'),
    url(r'^contact$', 'rock.views.contact_view', name='contact'),
    url(r'^search$', 'rock.views.search_view', name='search'),
    url(r'^activities$', 'rock.views.activities_view', name='activities'),
    url(r'^activity/(\w+)$', 'rock.views.activity_view', name='activity'),
    url(r'^join/(\w+)$', 'rock.views.join_view', name='join'),
    url(r'^leave/(\w+)$', 'rock.views.leave_view', name='leave'),
    url(r'^calendar$', 'rock.views.calendar_view', name='calendar'),
    # url(r'^rock/', include('rock.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

rock/models.py
from django.db import models
from django.contrib.auth.models import User

class Post(models.Model):
  title = models.CharField(max_length=1024)
  pub_date = models.DateTimeField('date published')
  body = models.TextField()

  def __unicode__(self):
    return self.title

class Tag(models.Model):
  slug = models.CharField(max_length=1024)
  body = models.TextField()

  def __unicode__(self):
    return self.slug

class TagSet(models.Model):
  slug = models.CharField(max_length=1024)
  title = models.CharField(max_length=1024)
  tags = models.ManyToManyField(Tag)
  highlighted = models.BooleanField()

  def __unicode__(self):
    return self.title

class Activity(models.Model):
  tag_set = models.ForeignKey(TagSet)
  users = models.ManyToManyField(User)
  slug = models.CharField(max_length=1024)
  title = models.CharField(max_length=1024)
  body = models.TextField()

  def __unicode__(self):
    return self.title

class Event(models.Model):
  month = models.CharField(max_length=10)
  activity = models.ForeignKey(Activity)

  def __unicode__(self):
    return self.month + " " + unicode(self.activity)

rock/views.py
from helpers import *
import random

def index_view(request):
    return Responder(request, 'landing.html', 'Home').response()

login_view = FormHandler(LoginForm, 'login.html', 'Login', 'Successfully logged in.', 'Failed to log in.', '/').responder()
signup_view = FormHandler(SignupForm, 'signup.html', 'Signup', 'Successfully signed up.', 'Failed to sign up.', '/').responder()
contact_view = FormHandler(PostForm, 'contact.html', 'Contact', 'Thanks for your feedback!', 'Please fill in all fields.', '/').responder()

def logout_view(request):
  logout(request)
  messages.success(request, "Successfully logged out.")
  return HttpResponseRedirect('/')

def activity_view(request, slug):
  activity = Activity.objects.get(slug=slug)
  is_into = False
  if request.user is not None:
    is_into = request.user in activity.users.all()
  r = Responder(request, 'activity.html', 'Activity', 'Get withinto...')
  r.add('activity', activity)
  r.add('is_into', is_into)
  r.add('num_into', len(activity.users.all()))
  return r.response()

def search_view(request):
  highlights = TagSet.objects.filter(highlighted=True)
  results = []
  slugs = []
  if request.method == "POST":
    print "POST", request.POST
    for v in request.POST:
      slugs.extend(request.POST.getlist(v))
    print "slugs", slugs
    for activity in Activity.objects.all():
      print "considering activity", activity
      for tag in activity.tag_set.tags.all():
        print "considering tag", tag
        if tag.slug in slugs:
          results.append(activity)
          break
  print "RESULTS", results
  random.shuffle(results)
  r = Responder(request, 'search.html', 'Search', 'Find wellness activities')
  r.add('highlights', highlights).add('results', results).add('slugs', slugs)
  r.add('num_results', len(results))
  return r.response()

@login_required(login_url='/login')
def join_view(request, slug):
  activity = Activity.objects.get(slug=slug)
  assert request.user and request.user not in activity.users.all()
  activity.users.add(request.user) 
  messages.success(request, "Joined "+activity.title)
  return HttpResponseRedirect("/activity/"+slug)

@login_required(login_url='/login')
def leave_view(request, slug):
  activity = Activity.objects.get(slug=slug)
  assert request.user and request.user in activity.users.all()
  activity.users.remove(request.user) 
  messages.success(request, "Left "+activity.title)
  return HttpResponseRedirect("/activity/"+slug)

@login_required(login_url='/login')
def activities_view(request):
  assert request.user
  results = []
  for activity in Activity.objects.all():
    if request.user in activity.users.all():
      results.append(activity)
  r = Responder(request, 'activities.html', 'Activities', 'Your activities')
  r.add('results', results)
  return r.response()

def calendar_view(request):
  r = Responder(request, 'calendar.html', 'Calendar', 'Monthly Health Challenge')
  for month in 'jan feb mar apr may jun jul aug sep oct nov dec'.split(' '):
    r.add(month+'acts', get_month_activities(month))
  return r.response()

rock/templates/activities.html
{% extends "layout.html" %}
{% block content %}

<div id="results" class="results">

  {% if results %}

    <p> Here's what you're withinto: </p>

    <table id="resultstable">
    {% for result in results %}

      <tr>
        <td>
          <a href="/activity/{{result.slug}}">{{ result.title }}</a>
        </td>
        <td>
          {{ result.body }}
        </td>
      </tr>

    {% endfor %}
    </table>

    <div id="tryme" class="floaty">
      <p>
        <a href="/search" class="btn btn-primary btn-large">Find some MORE activities!</a>
      </p>  
    </div>
  {% else %}
    <div id="tryme" class="floaty">
      <p>
        <a href="/search" class="btn btn-primary btn-large">Find some activities!</a>
      </p>  
    </div>
  {% endif %}

</div>

{% endblock %}

rock/templates/activity.html
{% extends "layout.html" %}
{% block content %}

<h3> {{ activity.title }} </h3>

<p> {{ activity.body }} </p>

{% if is_into %}
  {% if num_into == 0 %}
    <p> No one is into this yet. </p>
  {% elif num_into == 1 %}
    <p> Only you are into this.  Don't worry, more people will join you soon! </p>
  {% else %}
    <p> {{ num_results }} people are into this.  You will have a lot of fun!</p>
  {% endif %}
  <br/>
  <p><a href="/leave/{{ activity.slug }}" class="btn btn-large">Leave this activity.</a></p>
{% else %}
  {% if num_into == 0 %}
    <p> No one is into this yet.  Be the first! </p>
  {% elif num_into == 1 %}
    <p> Only one person is into this.  Join them! </p>
  {% else %}
    <p> {{ num_results }} other people are into this.  Join them! </p>
  {% endif %}
  <br/>
  <p><a href="/join/{{ activity.slug }}" class="btn btn-primary btn-large">Get withinto it!</a></p>
{% endif %}

{% endblock %}

rock/templates/contact.html
{% extends "layout.html" %}
{% block content %}

<br/>
<p> Send us some feedback! Be sure to leave your email or phone number so we can get back to you. Thanks! </p>
<br/>

<form action="/contact" method="POST">
  <p><label for="id_title">Subject:</label> <input type="text" name="title" id="id_title" /></p>
  <p><label for="id_body">Message:</label> <textarea name="body" id="id_body"></textarea></p>
  <p><input type="submit" value="Send" /></p>
</form>

{% endblock %}

rock/templates/landing.html
{% extends "layout.html" %}
{% block content %}

<div class="jumbotron floaty">
  <h1> Get Within </h1>
  <p><a href="/search" class="btn btn-large">Take your health and wellness to the next level!</a></p>
</div>

<div id="landingcarousel" class="carousel slide floaty">
  <div class="carousel-inner">
    <div class="active item">
      <h1> Are you... </h1>
      <ul>
        <li>
        <h2>Going through a life transition?</h2>
        <!--<ul>
          <li>Marriage</li>
          <li>Surgery</li>
          <li>Pregnancy</li>
          <li>Menopause</li>
          <li>Divorce</li>
        </ul>-->
        </li>
        <li>
        <h2>Turning a landmark age?</h2>
        <!--<ul>
          <li>30</li>
          <li>40</li>
          <li>45</li>
          <li>50</li>
          <li>60</li>
          <li>...ageless!</a>
      </ul>-->
        </li>
        <li>
        <h2>Just stoked about being alive and want to level up your vibrancy?</h2>
        <!--<ul>
          <li>Like to challenge yourself</li>
          <li>Marathon Runner</li>
          <li>Tri-athlete</li>
          <li>Just plain excited about being your best!</li>
        </ul>-->
        </li>
      </ul>
    </div>

    <div class="item">
      <h2>Join a vibrant community of health enthusiasts!</h2>
      <h3>How does it work?</h3>
      <p>People meet, are assigned personal coaches that help guide them to achieve wellness goals within the designated areas of Nutrition, Physical Wellness, and Spiritual Balance.</p>
      <p>They self-select from a cornucopia of <strong>local</strong> services, classes, workshops, treatments, events they want to attend and experience the magic of <strong>transformation</strong> together.</p>
      <p>They form support groups and activity buddies along the way to better living.</p>
    </div>

    <div class="item">
      <p>Your personal Coach will help you outline your goals in the different fields of health creation.</p>
      <p>They will begin with starting a health journal with your nutritional goals.</p>
      <h2>Options in your local area:</h2>
      <ul>
        <li>Professional nutritional consultation</li>
        <li>Cooking classes</li>
        <li>Aryuveda</li>
        <li>Raw foods classes</li>
        <li>Fitness classes</li>
        <li>Health care suggestions</li>
      </ul>
    </div>

  </div>

  <a class="carousel-control left" href="#landingcarousel" data-slide="prev">&lsaquo;</a>
  <a class="carousel-control right" href="#landingcarousel" data-slide="next">&rsaquo;</a>
</div>

<div id="tryme" class="floaty">
  <p>
    <a href="/search" class="btn btn-primary btn-large">Try it now!</a>
  </p>  
</div>

{% endblock %}

rock/templates/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>{{ title }}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
        font-size: 18px;
      }
      .messages {
        border: 1px solid black;
      }
      .messages li {
        padding: 10px;
      }
      .jumbotron {
        text-align: center;
        position: relative;
        padding: 20px 0px;
        text-shadow: 0 1px 3px rgba(0,0,0,.4), 0 0 30px rgba(0,0,0,.075);
        background-image: url('/static/img/banner.png');
        background-position: center;
        background-repeat: no-repeat;
        height: 300px;
        width: 954px;
        margin-left: auto;
        margin-right: auto;
        margin-bottom: 20px;
      }
      .jumbotron h1 {
        color: #eee;
        font-size: 80px;
        font-weight: bold;
        margin-bottom: 150px;
        /*background: #fff;*/
        padding: 20px;
      }
      .jumbotron a {
        color: #666;
        font-size: 24px;
        /*background: #fff;*/
        padding: 10px;
      }
      .carousel-inner {
        width: 700px;
        margin-left: auto;
        margin-right: auto;
      }
      .floaty {
        width: 954px;
        margin-left: auto;
        margin-right: auto;
      }
      #tryme {
        margin-top: 40px;
        text-align: center;
      }
      #tryme a {
        font-size: 40px;
      }
      #footer {
        text-align: center;
        margin-top: 40px;
        margin-bottom: 20px;
      }
      #resultstable td {
        padding: 10px;
      }
      #results {
        font-size: 20px;
      }
    </style>
    <link href="/static/css/bootstrap-responsive.css" rel="stylesheet">

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="/static/img/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/static/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/static/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/static/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="/static/ico/apple-touch-icon-57-precomposed.png">

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <!--<script src="/static/js/jquery.js"></script>
    <script src="/static/js/bootstrap-transition.js"></script>
    <script src="/static/js/bootstrap-alert.js"></script>
    <script src="/static/js/bootstrap-modal.js"></script>
    <script src="/static/js/bootstrap-dropdown.js"></script>
    <script src="/static/js/bootstrap-scrollspy.js"></script>
    <script src="/static/js/bootstrap-tab.js"></script>
    <script src="/static/js/bootstrap-tooltip.js"></script>
    <script src="/static/js/bootstrap-popover.js"></script>
    <script src="/static/js/bootstrap-button.js"></script>
    <script src="/static/js/bootstrap-collapse.js"></script>
    <script src="/static/js/bootstrap-carousel.js"></script>
    <script src="/static/js/bootstrap-typeahead.js"></script>-->
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">{{ name }}</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              {% for navname, navlink, isactive in navlinks %}
                {% if isactive %}
                  <li><a class="active" href="{{ navlink }}">{{ navname }}</a></li>
                {% else %}
                  <li><a href="{{ navlink }}">{{ navname }}</a></li>
                {% endif %}
              {% endfor %}
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">

      {% if messages %}
      <center>
      <ul class="messages">
          {% for message in messages %}
            {% if message.tags %}
              <li class="alert-{{ message.tags }}">{{ message }}</li>
            {% else %}
              <li class="alert-info">{{ message }}</li>
            {% endif %}
          {% endfor %}
      </ul>
      </center>
      {% endif %}

      <div class="floaty">
      {% if header %}
        <h1>{{ header }}</h1>
      {% endif %}

      {% block content %}
      {% endblock %}
      </div>

      <div class="floaty" id="footer">
        <hr/>
        <p>
        Built with pride in Santa Cruz, CA at <a href="http://techraising.com">Techraising</a> Fall 2012 by <a href="mailto:strazzeratibisay@gmail.com">Tibi Strazzera</a> and <a href="https://github.com/ejconlon">Eric Conlon</a>. <a href="https://github.com/ejconlon/getwithin">Open source</a>.
        </p>
      </div>

    </div> <!-- /container -->

  </body>
</html>

rock/templates/login.html
{% extends "layout.html" %}
{% block content %}

<form action="/login" method="POST">
  {{ form.as_p }}
  <input type="hidden" name="next" value="{{next}}"/>
  <p><input type="submit" value="Log in" /></p>
</form>

<p><a href="/signup?next={{next}}">Or signup.</a> (It's quick and easy!)</p>

{% endblock %}

rock/templates/search.html
{% extends "layout.html" %}
{% block content %}

<form action="/search" method="POST">

<p> I'm looking for something for... </p>

<div id="searchy">
{% for tagset in highlights %}
  <p><strong>{{ tagset.title }}</strong></p>
  <div class="btn-group tagset" data-toggle="buttons-checkbox">
    {% for tag in tagset.tags.all %}
      <button type="button" class="boxbtn btn" data-target="box-{{tagset.slug}}-{{tag.slug}}">{{tag.body}}</button>
      <input class="boxinput" id="box-{{tagset.slug}}-{{tag.slug}}" type="checkbox" name="{{tagset.slug}}" value="{{tag.slug}}" style="display: none;" {% if tag.slug in slugs %} checked {% endif %} /> 
    {% endfor %}
  </div>
  <br/>
{% endfor %}
</div>

<br/>
<p><input type="submit" value="Search" /></p>

</form>

<script type="text/javascript">
  $(document).ready(function(){
    $(".boxinput").each(function() {
      if ($(this).prop('checked')) {
        $("button[data-target="+$(this).prop('id')+"]").click();
      }
    });
    $(".boxbtn").click(function(){
      x = $(document.getElementById($(this).attr('data-target')));
      c = x.prop('checked');
      //alert('toggling '+x+' to !'+(c));
      x.prop('checked', !c);
    });
  });
</script>

<hr/>

<div id="results" class="results">

  {% if results %}

    <p> {{ num_results }} activities may interest you: </p>

    <table id="resultstable">
    {% for result in results %}

      <tr>
        <td>
          <a href="/activity/{{result.slug}}">{{ result.title }}</a>
        </td>
        <td>
          {{ result.body }}
        </td>
      </tr>

    {% endfor %}
    </table>

  {% else %}
    <p> No results found. </p>


  {% endif %}

</div>

{% endblock %}

rock/templates/signup.html
{% extends "layout.html" %}
{% block content %}

<form action="/signup" method="POST">
  {{ form.as_p }}
  <input type="hidden" name="next" value="{{next}}"/>
  <p><input type="submit" value="Sign up" /></p>
</form>

<p><a href="/login?next={{next}}">Or login.</a> (It's quick and easy!)</p>

{% endblock %}